spring:
  datasource:
    url: jdbc:mysql://121.5.79.74:3306/thyo_blogs?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: thyo_blogs
    password: qq121212
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:com/blogs/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
